### PR TITLE
Fix bug where class definition would get mangled.

### PR DESCRIPTION
**Pull request by m-kostrzewa**
Fixes https://github.com/DTW-DanWard/PowerShell-Beautifier/issues/34

### CODE REVIEW

**Comment by m-kostrzewa** [comment]
I don't like this fix, it still changes case sensitivity... I think names of user-defined classes shouldn't be touched at all.

**Comment by m-kostrzewa** [comment]
K seems kinda good now, but I don't like the hardcoded builtin types list. Any suggestions?

**Comment by DTW-DanWard** [comment]
I have an idea for this but need to test it.

**Comment by DTW-DanWard** [comment]
I like your approach; will merge but will get the actual type accelerators using:
```[psobject].assembly.gettype("System.Management.Automation.TypeAccelerators")::Get```

**Pull request merged**
